name: Sync Changelog

on:
  push:
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Hub
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://x-access-token:${{ secrets.HUB_TOKEN }}@github.com/jmsutorus/earthbound_changelog.git hub
          mkdir -p hub/content/repos/terra_docs
          cp CHANGELOG.md hub/content/repos/terra_docs/CHANGELOG.md
          cd hub
          git add .
          git commit -m "Update changelog for Terra Docs" || echo "No changes to commit"
          git push
